### ISSUE TITLE
create command to edit file

### ISSUE THREAD

**Issue by benaryorg** [lxc/lxd#1055]
You already have implemented the mechanism for editing a file on the calling system (`lxc config edit`) and there is a subcommand for files (`lxc file`).

Why not create a command with the syntax:

```bash
lxc file edit <source> [<source>...]
```

or similar?

**Comment by stgraber** [comment]
Note that "lxc config edit" doesn't actually edit a remote file, instead the client generates a local file based on the container state from the API, the user then edits it, the client parses it to see what you changed and then applies that remotely using the right API calls.

**Comment by benaryorg** [comment]
Yeah, I know that. What I wanted to say is that you already have a mechanism to create, edit, upload and delete a temporary file which is about 99% of the requirements to create the new command.

**Comment by stgraber** [comment]
Sure, would be easy enough to do.

Interested in implementing it yourself?

**Comment by benaryorg** [comment]
I could try it, sure.

**Comment by benaryorg** [comment]
I will inform you about the progress.

**Comment by benaryorg** [comment]
Is there a place to put globally used functions?

**Comment by benaryorg** [comment]
I have now pushed the first version to my own repo (to see if travis builds).

There are problems:

- if the file does not exist, an error is thrown
  - maybe implement a `--create` option to create an empty file
- the code for opening the editor could be placed in an external function to be used from everywhere
  - occurences
    - `lxc profile edit`
    - `lxc config edit`
    - `lxc file edit`

**Comment by stgraber** [comment]
Merged the first pass as it looked good enough.

Indeed, the editor code should be moved into a common function under shared/.
As for --create, maybe it'd be best to detect the pull failure and ask the user whether they want the file to be created for them? Note that this will still fail if the directory doesn't exist.

**Comment by benaryorg** [comment]
I didn't want to copy half of the code of the `lxc pull` command because I thought there might be a way of handling only that specific error, but I am new to Go at all so I left that to you for now.
I can edit existing files with `vim` without installing it inside every container. I am happy.

**Comment by benaryorg** [comment]
One could do something like

```
try edit
if error && (ask user) {
    try create file
    if error && (ask user) {
        try create directory && edit
        if error {
            return error
        }
    }
}
```

**Comment by tych0** [comment]
On Aug 28, 2015 9:26 AM, "Stéphane Graber" <notifications@github.com> wrote:
>
> Merged the first pass as it looked good enough.
>
> Indeed, the editor code should be moved into a common function under
shared/.

It isn't shared though. Shouldn't it just go into its own file in /lxc?

> As for --create, maybe it'd be best to detect the pull failure and ask
the user whether they want the file to be created for them? Note that this
will still fail if the directory doesn't exist.

**Comment by stgraber** [comment]
sure
