### ISSUE TITLE
Set log level of LXD and containers

### ISSUE THREAD

**Issue by jpillora** [lxc/lxd#2528]
How do you control the log level of the LXD daemon/containers? At the moment my log files are:

```
$ du -h /var/log/lxd/lxd.log
2.2G	/var/log/lxd/lxd.log
$ tail /var/log/lxd/lxd.log
...
t=2016-10-19T19:30:37+1100 lvl=info msg=handling method=GET url=/1.0/containers/my-cont/state ip=@
t=2016-10-19T19:30:38+1100 lvl=info msg=handling method=GET url=/1.0 ip=@
```

```
$ du -h /var/log/lxd/my-cont/lxc.log
8.9G	/var/log/lxd/my-cont/lxc.log
$ tail /var/log/lxd/my-cont/lxc.log
...
            lxc 20161019083216.651 DEBUG    lxc_commands - commands.c:lxc_cmd_get_state:579 - 'my-cont' is in 'RUNNING' state
            lxc 20161019083216.651 DEBUG    lxc_commands - commands.c:lxc_cmd_handler:893 - peer has disconnected
```

**Comment by stgraber** [comment]
So for /var/log/lxd/lxd.log it looks like we're missing a logrotate profile in the Ubuntu package.

For lxc.log, I'd be fine having lxc.log priority match the LXD logging level which should fix that too.

**Comment by stgraber** [comment]
Note that we've also reduced the amount of data we log by default recently, that's in LXD 2.0.5 and LXD 2.4.1, I'm assuming you're using 2.0.4 so things should improve a bit at least with that, even without the logrotate policy.

**Comment by jpillora** [comment]
Came up with this logrotate config:

```
$ cat /etc/logrotate.d/lxd
/var/log/lxd/lxd.log
/var/log/lxd/*/lxc.log
{
  rotate 4
  weekly
  create
  compress
  missingok
  notifempty
}
```

Ran first rotate with

```
logrotate -f /etc/logrotate.d/lxd
```

**Comment by stgraber** [comment]
So what I uploaded a few hours ago to Ubuntu is reasonably similar, except it rotates daily and only rotates /var/log/lxd/lxd.log as rotating /var/log/lxd/*/lxc.log would interfere with LXD's own log rotation, not to mention possibly confusing LXC in the process.

For the lxc.log side of this, the right fix is probably to adjust lxc.loglevel to a more appropriate value within LXD, which is what I'm using this github issue to track (since log rotation configuration is a packaging thing and therefore tracked on Launchpad).

**Comment by jpillora** [comment]
> the right fix is probably to adjust lxc.loglevel

What is this the correct way to do this? I tried the following and I was still seeing DEBUG logs

```
lxc config set mycont raw.lxc 'loglevel = 3'
```

**Comment by brauner** [comment]
The correct command would be

    lxc config set mycont raw.lxc 'lxc.loglevel = 3'

**Comment by brauner** [comment]
We only report invalid low-level `LXC` config keys when they start with `lxc.*`. So you would receive an error on `lxc config set c3 raw.lxc 'lxc.asdf = 3'` but not on `lxc config set mycont raw.lxc 'loglevel = 3'`. This makes me wonder whether we should actually also error out on lines that are not commented out and do not start with `lxc.`. This would require a fix in `LXC`.

**Comment by stgraber** [comment]
In LXC, it's intentional that keys not starting with lxc.* are allowed and don't cause parser errors, that's so downstream tools based on LXC can store settings in the container config.

**Comment by brauner** [comment]
Right, that's sort of what I expected.
