### ISSUE TITLE
"error: No storage pool specified." after upgrade lxd to 2.9.1

### ISSUE THREAD

**Issue by mgregal** [lxc/lxd#2905]
## Required Information
 * Distribution: lubuntu 
 * Distribution version: 16.04.2 LTS
 * The output of "lxc info::
```
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFRjCCAy6gAwIBAgIQUMwlqmF+TOJrioPa/pyE0DANBgkqhkiG9w0BAQsFADA2
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRYwFAYDVQQDDA1yb290QHBj
    bWFudWVsMB4XDTE2MTIyNzEyMTEzOFoXDTI2MTIyNTEyMTEzOFowNjEcMBoGA1UE
    ChMTbGludXhjb250YWluZXJzLm9yZzEWMBQGA1UEAwwNcm9vdEBwY21hbnVlbDCC
    AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBALBspNcymKEEw/xADobg9MFI
    06rp0FBy7zPJ6lOOr6duKcRv83q/xC9UaMmqje4XNNJLKNIhvjTVjeRuNP4DxuAz
    wU3aYID5R3k/8llOFencIuSxq4aaBemcSZr8LQK0DucbJ0rEua6dKgQbXENxTtIY
    oLwTGjW/EfHbahpFSvK0E3XkFVojXTMhaInCcSXFihhVOzvPBKW+swB5hDIBi35m
    oUuYi1c2K/KNenSBcID0+qY1kIv/H3FwH3W2mUvebsdc/EgaT49E9H0GY77P6wj7
    ovk3qF+LyKF7b/CCReyxpgYroC19Ih6pi7jE5eDXTGl7ALoEtoIuIoPoF9vl600J
    b1KAZCZhxKgf6eO0rRGSDl+RVc6dklDupxa4d764/Fu6FoDGBUqQ+2+LTC4FN/i4
    xgQfQew4eMGM7PUCMwwg0o8ezEsA7nt6IWtJv7oel1DPdmOJqtOi2hLHHVJ2u47K
    bIbER3y7e8KRC68M6gQdatyH+VV+Hhcngso5lBAcH3oBQCB5FtbYAWAgBxhktd9+
    PmtlvQgV4gPwtipnh5dlRBIp5I4x1nSuu64ALONjzacKkkssjR/xbIYjp4dsw2E7
    rFY9oIBEDTn7SBMegTBY0Tk8vM3XKkVOpaZV+IjQTU673N0yVcCN8aVaKIMCDRH5
    czRtHrUK6nVr1kuDdpyFAgMBAAGjUDBOMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUE
    DDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMBkGA1UdEQQSMBCCCHBjbWFudWVs
    hwTAqAEsMA0GCSqGSIb3DQEBCwUAA4ICAQAUkyyt9i27e+Uy8Ee4htVfoIMHiN9D
    C0tJ5MJun6ye7JwP0SR4t4m/fq36h8/iGn+g8IVifzObeW5w+aoIEFLNsPzg7Ivs
    +NVhdylEJGquU1ZtXAk2+JNrnZ5qZWVFrlKN5SXhNrF8A3TTQjnZrXNLC/+/NImW
    cXsxNczEkXUswnx7J99uK12LoRz+EEFhyi1TKF1zF5QHybjYxgKdcFSt3ILviXp7
    DwQ/dEZzEC28I0Ztrn9JuQOW3k0v2NqQdpTEZU2U27cMlP+UCQlc2b4wi89S4BE3
    gsa5ZnJfCUYcTQ4q+8H228TEs7mgVMZ6RDXaBdUl2cg974XFvgFSw/VW2clJrTh7
    ForEl2kP7Fzkdmph3n4rdp2vOhkqt+f1iuyi2ngFCR8psExbH5mhJMKZcBeWDNNm
    Xngm/Q7MS0jSwUYvvCmMEwBgvqDuoG8L1QBbe5j+WL0RYz+aCdWg18nHG2sV1J3H
    VH+AygVi9UUQe22yyBKsa0xOr+SrbFg3TGQXhdI8RTynRcSL5TgwsKNxVfEJNUpL
    je1mxPbV1JUlASKzA9RRNCoQnbklBjgZ8Xf7rEsuUqwrajhjRDFNeZ+0PfKPYx7X
    SWbgc02DBR/HDv2y24qvmXHHoawJc8/tQX6L32PdIP3h/xCz2DgfomeIJHicVCbq
    z0+3osJShnp2Yg==
    -----END CERTIFICATE-----
  certificate_fingerprint: d6052c34cef7200ea3c4d90b7f358da514deb515a3858e00e2b4a9fe0effa595
  driver: lxc
  driver_version: 2.0.7
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-62-generic
  server: lxd
  server_pid: 2358
  server_version: 2.9.1
  storage: zfs
  storage_version: 0.6.5.6-0ubuntu15
```
## Issue description
After upgrade lxd to 2.9.1 version, all containers are working except one. When I try to start this container appears that mesage: `error: No storage pool specified`. ZFS pool is ok and the files associated with the container seem to be ok.

## Information to attach
lxc ls: the container proxy is in status ERROR
```
manuel@pcmanuel:~$ lxc ls -c n,s,4,6,P,S,l,t
+------------+---------+----------------------+------+----------+-----------+----------------------+------------+
|   NOMBRE   | ESTADO  |         IPV4         | IPV6 | PERFILES | SNAPSHOTS |     LAST USED AT     |    TIPO    |
+------------+---------+----------------------+------+----------+-----------+----------------------+------------+
| apt-cacher | RUNNING | 192.168.1.254 (eth0) |      | default  | 0         | 2017/02/18 20:47 UTC | PERSISTENT |
+------------+---------+----------------------+------+----------+-----------+----------------------+------------+
| proxy      | ERROR   |                      |      |          |           |                      | PERSISTENT |
+------------+---------+----------------------+------+----------+-----------+----------------------+------------+
| server01   | STOPPED |                      |      | default  | 0         | 2017/02/18 20:49 UTC | PERSISTENT |
+------------+---------+----------------------+------+----------+-----------+----------------------+------------+
| vsftpd     | STOPPED |                      |      | default  | 0         | 2017/02/18 20:01 UTC | PERSISTENT |
+------------+---------+----------------------+------+----------+-----------+----------------------+------------+

```
Start proxy container:
```
manuel@pcmanuel:~$ lxc start proxy
error: No storage pool specified.
manuel@pcmanuel:~$ lxc start --debug proxy
DBUG[02-19|00:35:25] Raw response: {"type":"sync","status":"Success","status_code":200,"operation":"","error_code":0,"error":"","metadata":{"config":{},"api_extensions":["storage_zfs_remove_snapshots","container_host_shutdown_timeout","container_syscall_filtering","auth_pki","container_last_used_at","etag","patch","usb_devices","https_allowed_credentials","image_compression_algorithm","directory_manipulation","container_cpu_time","storage_zfs_use_refquota","storage_lvm_mount_options","network","profile_usedby","container_push","container_exec_recording","certificate_update","container_exec_signal_handling","gpu_devices","container_image_properties","migration_progress","id_map","network_firewall_filtering","network_routes","storage","file_delete","file_append","network_dhcp_expiry"],"api_status":"stable","api_version":"1.0","auth":"trusted","public":false,"environment":{"addresses":[],"architectures":["x86_64","i686"],"certificate":"-----BEGIN CERTIFICATE-----\nMIIFRjCCAy6gAwIBAgIQUMwlqmF+TOJrioPa/pyE0DANBgkqhkiG9w0BAQsFADA2\nMRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRYwFAYDVQQDDA1yb290QHBj\nbWFudWVsMB4XDTE2MTIyNzEyMTEzOFoXDTI2MTIyNTEyMTEzOFowNjEcMBoGA1UE\nChMTbGludXhjb250YWluZXJzLm9yZzEWMBQGA1UEAwwNcm9vdEBwY21hbnVlbDCC\nAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBALBspNcymKEEw/xADobg9MFI\n06rp0FBy7zPJ6lOOr6duKcRv83q/xC9UaMmqje4XNNJLKNIhvjTVjeRuNP4DxuAz\nwU3aYID5R3k/8llOFencIuSxq4aaBemcSZr8LQK0DucbJ0rEua6dKgQbXENxTtIY\noLwTGjW/EfHbahpFSvK0E3XkFVojXTMhaInCcSXFihhVOzvPBKW+swB5hDIBi35m\noUuYi1c2K/KNenSBcID0+qY1kIv/H3FwH3W2mUvebsdc/EgaT49E9H0GY77P6wj7\novk3qF+LyKF7b/CCReyxpgYroC19Ih6pi7jE5eDXTGl7ALoEtoIuIoPoF9vl600J\nb1KAZCZhxKgf6eO0rRGSDl+RVc6dklDupxa4d764/Fu6FoDGBUqQ+2+LTC4FN/i4\nxgQfQew4eMGM7PUCMwwg0o8ezEsA7nt6IWtJv7oel1DPdmOJqtOi2hLHHVJ2u47K\nbIbER3y7e8KRC68M6gQdatyH+VV+Hhcngso5lBAcH3oBQCB5FtbYAWAgBxhktd9+\nPmtlvQgV4gPwtipnh5dlRBIp5I4x1nSuu64ALONjzacKkkssjR/xbIYjp4dsw2E7\nrFY9oIBEDTn7SBMegTBY0Tk8vM3XKkVOpaZV+IjQTU673N0yVcCN8aVaKIMCDRH5\nczRtHrUK6nVr1kuDdpyFAgMBAAGjUDBOMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUE\nDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMBkGA1UdEQQSMBCCCHBjbWFudWVs\nhwTAqAEsMA0GCSqGSIb3DQEBCwUAA4ICAQAUkyyt9i27e+Uy8Ee4htVfoIMHiN9D\nC0tJ5MJun6ye7JwP0SR4t4m/fq36h8/iGn+g8IVifzObeW5w+aoIEFLNsPzg7Ivs\n+NVhdylEJGquU1ZtXAk2+JNrnZ5qZWVFrlKN5SXhNrF8A3TTQjnZrXNLC/+/NImW\ncXsxNczEkXUswnx7J99uK12LoRz+EEFhyi1TKF1zF5QHybjYxgKdcFSt3ILviXp7\nDwQ/dEZzEC28I0Ztrn9JuQOW3k0v2NqQdpTEZU2U27cMlP+UCQlc2b4wi89S4BE3\ngsa5ZnJfCUYcTQ4q+8H228TEs7mgVMZ6RDXaBdUl2cg974XFvgFSw/VW2clJrTh7\nForEl2kP7Fzkdmph3n4rdp2vOhkqt+f1iuyi2ngFCR8psExbH5mhJMKZcBeWDNNm\nXngm/Q7MS0jSwUYvvCmMEwBgvqDuoG8L1QBbe5j+WL0RYz+aCdWg18nHG2sV1J3H\nVH+AygVi9UUQe22yyBKsa0xOr+SrbFg3TGQXhdI8RTynRcSL5TgwsKNxVfEJNUpL\nje1mxPbV1JUlASKzA9RRNCoQnbklBjgZ8Xf7rEsuUqwrajhjRDFNeZ+0PfKPYx7X\nSWbgc02DBR/HDv2y24qvmXHHoawJc8/tQX6L32PdIP3h/xCz2DgfomeIJHicVCbq\nz0+3osJShnp2Yg==\n-----END CERTIFICATE-----\n","certificate_fingerprint":"","driver":"lxc","driver_version":"2.0.7","kernel":"Linux","kernel_architecture":"x86_64","kernel_version":"4.4.0-62-generic","server":"lxd","server_pid":2358,"server_version":"2.9.1","storage":"zfs","storage_version":"0.6.5.6-0ubuntu15"}}}
 
DBUG[02-19|00:35:25] Raw response: {"error":"No storage pool specified.","error_code":500,"type":"error"}

 
error: No storage pool specified.
```
Status of zfs pool:
```
manuel@pcmanuel:~$ sudo zpool status
  pool: lxd
 state: ONLINE
  scan: scrub repaired 0 in 0h0m with 0 errors on Sun Jan  8 00:24:33 2017
config:

	NAME        STATE     READ WRITE CKSUM
	lxd         ONLINE       0     0     0
	  sdc       ONLINE       0     0     0

errors: No known data errors
manuel@pcmanuel:~$ sudo sudo zpool list
NAME   SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
lxd    464G  1,90G   462G         -     0%     0%  1.00x  ONLINE  -
manuel@pcmanuel:~$ sudo zfs list
NAME                                                                                  USED  AVAIL  REFER  MOUNTPOINT
lxd                                                                                  1,90G   448G    96K  none
lxd/containers                                                                        503M   448G    96K  none
lxd/containers/apt-cacher                                                             139M   448G   428M  /var/lib/lxd/storage-pools/lxd/containers/apt-cacher
lxd/containers/proxy                                                                  109M   448G   412M  /var/lib/lxd/storage-pools/lxd/containers/proxy
lxd/containers/server01                                                              43,2M   448G   360M  /var/lib/lxd/storage-pools/lxd/containers/server01
lxd/containers/vsftpd                                                                 212M   448G   481M  /var/lib/lxd/storage-pools/lxd/containers/vsftpd
lxd/deleted                                                                          1,05G   448G    96K  none
lxd/deleted/images                                                                   1,05G   448G    96K  none
lxd/deleted/images/5f19596a09c19d4beed653de08ea438c32e2fee35a10c6963a8285cae95c0a43   360M   448G   360M  none
lxd/deleted/images/8573fa6fed57ecadbb6f76f6b424533e4a8c5a562e29cee28ba47b6923aa4f88   360M   448G   360M  none
lxd/deleted/images/d57cf522816f735c132b9eac444e86557c9b43e30dde7ba0dc61a7dbde3933a6   360M   448G   360M  none
lxd/images                                                                            361M   448G    96K  none
lxd/images/3b825a6a063aacc6b19df84f7ddc4fe872a0e382ec0bb92f475a9493b0857e01           360M   448G   360M  none
```
Files: 
```
manuel@pcmanuel:~$ ls -lahF /var/lib/lxd/storage-pools/lxd/containers/proxy 
total 39K
drwxr-xr-x  4 165536 165536    6 ene 24 12:19 ./
drwx--x--x  6 root   root   4,0K feb 18 21:53 ../
-r--------  1 root   root   2,4K feb 18 01:34 backup.yaml
-rw-r--r--  1 root   root   1,5K ene 10 21:52 metadata.yaml
drwxr-xr-x 22 165536 165536   23 ene 24 16:59 rootfs/
drwxr-xr-x  2 root   root      8 ene 10 21:52 templates/
```

Container log:
```
manuel@pcmanuel:~$ lxc info proxy --show-log
error: No storage pool specified.
```

**Comment by brauner** [comment]
Hi, can you please show the output of:

- sqlite3 /var/lib/lxd/lxd.db "SELECT name FROM storage_pools"
- sqlite3 /var/lib/lxd/lxd.db "SELECT name FROM storage_volumes"

**Comment by stgraber** [comment]
@brauner the reason for the failure here is that the "proxy" container doesn't use any profiles and LXD didn't fill the "pool" property on upgrade. It's the same problem that's hitting people who migrate containers from pre-2.9 to 2.9 as the container will have a "root" disk entry but no pool property, leading to the container failing to start.

@mgregal You can try:

    lxc config device set proxy root pool default

I'm not sure it's going to work though as that pool config check seems to be triggering even when reading the container's config...

**Comment by brauner** [comment]
@stgraber, actually the upgrade fills in the storage pool device. Only when the default profile isn't find it won't. We could try on upgrade to give each container that is not on the default profile it's local root disk device.

**Comment by stgraber** [comment]
@brauner I think we need something like this.

On upgrade:
 - Update the default profile
 - Iterate through all existing containers
   - Find where the container's root is stored (mentioned later as CTPOOL)
   - Check ExpandedDevices for a valid root entry (type=disk path=/ pool=CTPOOL), if found, skip to next container
   - Set the local root disk in Devices to have a pool property pointing to CTPOOL

On copy:
   - Find where the container's root is stored (mentioned later as CTPOOL)
   - Check ExpandedDevices for a valid root entry (type=disk path=/ pool=CTPOOL), if found, skip to next container
   - Set the local root disk in Devices to have a pool property pointing to CTPOOL

That should take care of the upgrade problem when people have a container which doesn't use the default profile and will also take care of the copying from an older LXD problem as it'll fill the pool property as needed on copy.

Does that seem reasonable?

**Comment by mgregal** [comment]
@stgraber 
`lxc config device set proxy root pool default` don't work for me:
```
manuel@pcmanuel:~$ lxc config device set proxy root pool default
error: No storage pool specified.
```
But your answer and the conversation with brauner makes me to see that the "proxy" container has a specific profile (2NICs). I compared the default and the proxy profile and saw the differences. The proxy profile 2NICs haven't got defined a root disk device. I proceed to add the root disk device and the zfs pool and it works!. Now the profile is:
```
manuel@pcmanuel:~$ lxc profile show 2NICs
config: {}
description: ""
devices:
  eth0:
    nictype: bridged
    parent: br0
    type: nic
  eth1:
    name: eth1
    nictype: bridged
    parent: int172-16
    type: nic
  root:
    path: /
    pool: lxd
    type: disk
name: 2NICs
used_by:
- /1.0/containers/proxy
```
Now the container is working
```
manuel@pcmanuel:~$ lxc ls -c n,s,4,6,P,S,l,t
+------------+---------+--------------------------------+------+----------+-----------+----------------------+------------+
|   NOMBRE   | ESTADO  |              IPV4              | IPV6 | PERFILES | SNAPSHOTS |     LAST USED AT     |    TIPO    |
+------------+---------+--------------------------------+------+----------+-----------+----------------------+------------+
| apt-cacher | STOPPED |                                |      | default  | 0         | 2017/02/18 20:47 UTC | PERSISTENT |
+------------+---------+--------------------------------+------+----------+-----------+----------------------+------------+
| proxy      | RUNNING | 192.168.1.253 (eth0)           |      | 2NICs    | 0         | 2017/02/19 16:09 UTC | PERSISTENT |
|            |         | 172.16.255.253 (eth1)          |      |          |           |                      |            |
+------------+---------+--------------------------------+------+----------+-----------+----------------------+------------+
| proxy2     | STOPPED |                                |      | 2NICs    | 0         |                      | PERSISTENT |
+------------+---------+--------------------------------+------+----------+-----------+----------------------+------------+
| server01   | STOPPED |                                |      | default  | 0         | 2017/02/18 20:49 UTC | PERSISTENT |
+------------+---------+--------------------------------+------+----------+-----------+----------------------+------------+
| vsftpd     | STOPPED |                                |      | default  | 0         | 2017/02/18 20:01 UTC | PERSISTENT |
+------------+---------+--------------------------------+------+----------+-----------+----------------------+------------+

```
Without the root disk device into the profile the container proxy can't start and even I can't create a new container using that profile. 
Thanks for the answer and your fantastic work

**Comment by mgregal** [comment]
@brauner 
Hi, the problem is solved but the outputs:
```
manuel@pcmanuel:~$ sqlite3 /var/lib/lxd/lxd.db "SELECT name FROM storage_pools"
lxd
manuel@pcmanuel:~$ sqlite3 /var/lib/lxd/lxd.db "SELECT name FROM storage_volumes"
apt-cacher
proxy
server01
vsftpd
3b825a6a063aacc6b19df84f7ddc4fe872a0e382ec0bb92f475a9493b0857e01
```
apt-cacher, server01, vsftpd are containers using the default profile
proxy is the problematic container using a special profile 
3b825a6a.. is an image ubuntu 14.04 64 bits

Thanks and salutes from Spain

**Comment by brauner** [comment]
@mgregal, cool. Glad that problem was solved. There will be a couple of improvements to profile handling in the next release that should avoid these issues.
@stgraber, sounds good so far. I will implement tomorrow and see whether it all works out or if I need adaptions.

**Comment by brauner** [comment]
@stgraber, also the issue with setting the storage pools with `lxc config device set ...` should be addressed in PR https://github.com/lxc/lxd/pull/2903, specifically:

-  https://github.com/lxc/lxd/pull/2903/commits/0e9fb70c3f24857c2adc92c79ec00a1c053eaa79
and
- https://github.com/lxc/lxd/pull/2903/commits/cbd2b0feac32a0eb484a8e35fc60622d2b5773f1

**Comment by dulinux** [comment]
Same issue here. All my containers were created with a custom profile and I got the storage pool error when trying to start them:

`error: No storage pool specified.`

After editing the custom profile and inserting the root device entry everything is working again:

```
~$ lxc profile edit bridged

devices:
  root:
    path: /
    pool: default
    type: disk
```

**Comment by cerealcable** [comment]
I also had this issue (or similar) and definitely was not expecting a minor version bump to cause such a large issue. Definitely would recommend pulling 2.9 from the stable PPA until it is further tested.

Here's my upgrade log:
```
$ sudo apt dist-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  lxd lxd-client snap-confine snapd ubuntu-core-launcher
5 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 13.6 MB of archives.
After this operation, 534 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 snapd amd64 2.22.3 [8,741 kB]
Get:2 http://ppa.launchpad.net/ubuntu-lxc/lxd-stable/ubuntu xenial/main amd64 lxd amd64 2.9.1-0ubuntu3~ubuntu16.04.1~ppa1 [2,818 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 ubuntu-core-launcher amd64 2.22.3 [1,578 B]
Get:4 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 snap-confine amd64 2.22.3 [41.5 kB]
Get:5 http://ppa.launchpad.net/ubuntu-lxc/lxd-stable/ubuntu xenial/main amd64 lxd-client amd64 2.9.1-0ubuntu3~ubuntu16.04.1~ppa1 [1,950 kB]
Fetched 13.6 MB in 3s (3,392 kB/s)      
(Reading database ... 114402 files and directories currently installed.)
Preparing to unpack .../snapd_2.22.3_amd64.deb ...
Warning: Stopping snapd.service, but it can still be activated by:
  snapd.socket
Unpacking snapd (2.22.3) over (2.22.2) ...
Preparing to unpack .../ubuntu-core-launcher_2.22.3_amd64.deb ...
Unpacking ubuntu-core-launcher (2.22.3) over (2.22.2) ...
Preparing to unpack .../snap-confine_2.22.3_amd64.deb ...
Unpacking snap-confine (2.22.3) over (2.22.2) ...
Preparing to unpack .../lxd_2.9.1-0ubuntu3~ubuntu16.04.1~ppa1_amd64.deb ...
Warning: Stopping lxd.service, but it can still be activated by:
  lxd.socket
Unpacking lxd (2.9.1-0ubuntu3~ubuntu16.04.1~ppa1) over (2.8-0ubuntu1~ubuntu16.04.1~ppa1) ...
Preparing to unpack .../lxd-client_2.9.1-0ubuntu3~ubuntu16.04.1~ppa1_amd64.deb ...
Unpacking lxd-client (2.9.1-0ubuntu3~ubuntu16.04.1~ppa1) over (2.8-0ubuntu1~ubuntu16.04.1~ppa1) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for ureadahead (0.100.0-19) ...
ureadahead will be reprofiled on next reboot
Processing triggers for systemd (229-4ubuntu16) ...
Setting up snap-confine (2.22.3) ...
Setting up snapd (2.22.3) ...
Setting up ubuntu-core-launcher (2.22.3) ...
Setting up lxd-client (2.9.1-0ubuntu3~ubuntu16.04.1~ppa1) ...
Setting up lxd (2.9.1-0ubuntu3~ubuntu16.04.1~ppa1) ...
Job for lxd-containers.service failed because the control process exited with error code. See "systemctl status lxd-containers.service" and "journalctl -xe" for details.
lxd-containers.service couldn't restart.
```

Looking at the details...
```
$ systemctl status lxd-containers.service
● lxd-containers.service - LXD - container startup/shutdown
   Loaded: loaded (/lib/systemd/system/lxd-containers.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2017-02-19 22:29:37 CST; 3min 8s ago
     Docs: man:lxd(1)
  Process: 24126 ExecStop=/usr/lib/lxd/shutdown (code=exited, status=0/SUCCESS)
  Process: 24132 ExecStart=/usr/bin/lxd activateifneeded (code=exited, status=1/FAILURE)
 Main PID: 24132 (code=exited, status=1/FAILURE)

Feb 19 22:29:37 hyper systemd[1]: Starting LXD - container startup/shutdown...
Feb 19 22:29:37 hyper lxd[24132]: error: No storage pool specified.
Feb 19 22:29:37 hyper systemd[1]: lxd-containers.service: Main process exited, code=exited, status=1/FAILURE
Feb 19 22:29:37 hyper systemd[1]: Failed to start LXD - container startup/shutdown.
Feb 19 22:29:37 hyper systemd[1]: lxd-containers.service: Unit entered failed state.
Feb 19 22:29:37 hyper systemd[1]: lxd-containers.service: Failed with result 'exit-code'.
```

```
$ systemctl status lxd-containers.service
● lxd-containers.service - LXD - container startup/shutdown
   Loaded: loaded (/lib/systemd/system/lxd-containers.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2017-02-19 22:29:37 CST; 3min 8s ago
     Docs: man:lxd(1)
  Process: 24126 ExecStop=/usr/lib/lxd/shutdown (code=exited, status=0/SUCCESS)
  Process: 24132 ExecStart=/usr/bin/lxd activateifneeded (code=exited, status=1/FAILURE)
 Main PID: 24132 (code=exited, status=1/FAILURE)

Feb 19 22:29:37 hyper systemd[1]: Starting LXD - container startup/shutdown...
Feb 19 22:29:37 hyper lxd[24132]: error: No storage pool specified.
Feb 19 22:29:37 hyper systemd[1]: lxd-containers.service: Main process exited, code=exited, status=1/FAILURE
Feb 19 22:29:37 hyper systemd[1]: Failed to start LXD - container startup/shutdown.
Feb 19 22:29:37 hyper systemd[1]: lxd-containers.service: Unit entered failed state.
Feb 19 22:29:37 hyper systemd[1]: lxd-containers.service: Failed with result 'exit-code'.
```

The following command was just blocked w/o any return value:
```
$ lxc storage list
^C
```

lxd-containers was in a failed status:
```
$ systemctl status lxd-containers
● lxd-containers.service - LXD - container startup/shutdown
   Loaded: loaded (/lib/systemd/system/lxd-containers.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2017-02-19 22:29:37 CST; 7min ago
     Docs: man:lxd(1)
  Process: 24126 ExecStop=/usr/lib/lxd/shutdown (code=exited, status=0/SUCCESS)
  Process: 24132 ExecStart=/usr/bin/lxd activateifneeded (code=exited, status=1/FAILURE)
 Main PID: 24132 (code=exited, status=1/FAILURE)

Feb 19 22:29:37 hyper systemd[1]: Starting LXD - container startup/shutdown...
Feb 19 22:29:37 hyper lxd[24132]: error: No storage pool specified.
Feb 19 22:29:37 hyper systemd[1]: lxd-containers.service: Main process exited, code=exited, status=1/FAILURE
Feb 19 22:29:37 hyper systemd[1]: Failed to start LXD - container startup/shutdown.
Feb 19 22:29:37 hyper systemd[1]: lxd-containers.service: Unit entered failed state.
Feb 19 22:29:37 hyper systemd[1]: lxd-containers.service: Failed with result 'exit-code'.
```

I poked at the database and saw:
```
$ sqlite3 /var/lib/lxd/lxd.db 'SELECT name FROM storage_volumes'
bitnode
```
Odd note, bitnode is just a name of one of my containers, not sure that I was expecting to see that?

At this point I decided it was best to downgrade and worry about this another day, for those wondering, this is how it worked for me:
```
$ sudo apt install lxd=2.8-0ubuntu1~ubuntu16.04.1 lxd-client=2.8-0ubuntu1~ubuntu16.04.1
```

I also copied over the backup db and restarted everything after that, thankfully that was done during the upgrade process for us.

**Comment by stgraber** [comment]
It's somewhat surprising that the downgrade worked, I'd have expected the upgrade to 2.9 to move enough of the containers to the new paths that LXD 2.8 wouldn't be able to make sense of them.

I'd strongly recommend you don't stop or restart any of your existing containers as chances are that will fail due to them having been relocated.

**Comment by stgraber** [comment]
Also, LXD 2.8 and LXD 2.9 are full feature releases of LXD which come with newly added features. We only bump the major version (LXD 2.x vs 3.x) every couple of years when we do API breaking changes.

The LTS branch that only gets bugfixes and security updates is LXD 2.0.x, that one will not see any feature addition at all between releases.

**Comment by stgraber** [comment]
@cerealcable Can you paste "journalctl --unit=lxd"? With a bit of luck, it'll contain the original upgrade failure.

The output of "lxc info" and "lxc config show" would also be useful

**Comment by cerealcable** [comment]
If it helps I am running on zfs, not sure if that matters.

```
# journalctl --unit=lxd
-- Logs begin at Fri 2017-02-17 16:31:04 CST, end at Sun 2017-02-19 23:17:01 CST. --
Feb 17 16:31:29 hyper systemd[1]: Starting LXD - main daemon...
Feb 17 16:31:29 hyper lxd[5010]: lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2017-02-17T16:31:29-0600
Feb 17 16:31:39 hyper lxd[5010]: lvl=warn msg="Unable to refresh cache, using stale entry" server=https://cloud-images.ubuntu.com/releases t=2017-02-17T16:31:39-0600
Feb 17 16:31:56 hyper systemd[1]: Started LXD - main daemon.
Feb 19 22:29:31 hyper systemd[1]: Stopping LXD - main daemon...
Feb 19 22:29:31 hyper systemd[1]: Stopped LXD - main daemon.
Feb 19 22:33:55 hyper systemd[1]: Starting LXD - main daemon...
Feb 19 22:33:55 hyper lxd[24799]: lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2017-02-19T22:33:55-0600
Feb 19 22:34:06 hyper lxd[24799]: error: Failed to unmount ZFS filesystem: umount: /var/lib/lxd/containers/bitnode.zfs: target is busy
Feb 19 22:34:06 hyper lxd[24799]:         (In some cases useful info about processes that
Feb 19 22:34:06 hyper lxd[24799]:          use the device is found by lsof(8) or fuser(1).)
Feb 19 22:34:06 hyper lxd[24799]: cannot unmount '/var/lib/lxd/containers/bitnode.zfs': umount failed
Feb 19 22:34:06 hyper systemd[1]: lxd.service: Main process exited, code=exited, status=1/FAILURE
Feb 19 22:43:27 hyper systemd[1]: Stopped LXD - main daemon.
Feb 19 22:43:27 hyper systemd[1]: lxd.service: Unit entered failed state.
Feb 19 22:43:27 hyper systemd[1]: lxd.service: Failed with result 'exit-code'.
Feb 19 22:43:27 hyper systemd[1]: Starting LXD - main daemon...
Feb 19 22:43:27 hyper lxd[27078]: lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2017-02-19T22:43:27-0600
Feb 19 22:43:27 hyper lxd[27078]: error: UNIQUE constraint failed: storage_pools.name
Feb 19 22:43:27 hyper systemd[1]: lxd.service: Main process exited, code=exited, status=1/FAILURE
Feb 19 22:45:46 hyper systemd[1]: Stopped LXD - main daemon.
Feb 19 22:45:46 hyper systemd[1]: lxd.service: Unit entered failed state.
Feb 19 22:45:46 hyper systemd[1]: lxd.service: Failed with result 'exit-code'.
Feb 19 22:45:46 hyper systemd[1]: Starting LXD - main daemon...
Feb 19 22:45:46 hyper lxd[27430]: lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2017-02-19T22:45:46-0600
Feb 19 22:45:46 hyper lxd[27430]: error: UNIQUE constraint failed: storage_pools.name
Feb 19 22:45:46 hyper systemd[1]: lxd.service: Main process exited, code=exited, status=1/FAILURE
Feb 19 22:45:56 hyper systemd[1]: Stopped LXD - main daemon.
Feb 19 22:45:56 hyper systemd[1]: lxd.service: Unit entered failed state.
Feb 19 22:45:56 hyper systemd[1]: lxd.service: Failed with result 'exit-code'.
Feb 19 22:45:56 hyper systemd[1]: Starting LXD - main daemon...
Feb 19 22:45:56 hyper lxd[27482]: lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2017-02-19T22:45:56-0600
Feb 19 22:45:56 hyper lxd[27482]: error: UNIQUE constraint failed: storage_pools.name
Feb 19 22:45:56 hyper systemd[1]: lxd.service: Main process exited, code=exited, status=1/FAILURE
Feb 19 22:45:59 hyper systemd[1]: Stopped LXD - main daemon.
Feb 19 22:45:59 hyper systemd[1]: lxd.service: Unit entered failed state.
Feb 19 22:45:59 hyper systemd[1]: lxd.service: Failed with result 'exit-code'.
Feb 19 22:46:12 hyper systemd[1]: Starting LXD - main daemon...
Feb 19 22:46:12 hyper lxd[27548]: lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2017-02-19T22:46:12-0600
Feb 19 22:46:12 hyper lxd[27548]: error: UNIQUE constraint failed: storage_pools.name
Feb 19 22:46:12 hyper systemd[1]: lxd.service: Main process exited, code=exited, status=1/FAILURE
Feb 19 22:52:05 hyper systemd[1]: Stopped LXD - main daemon.
Feb 19 22:52:05 hyper systemd[1]: lxd.service: Unit entered failed state.
Feb 19 22:52:05 hyper systemd[1]: lxd.service: Failed with result 'exit-code'.
Feb 19 22:52:05 hyper systemd[1]: Starting LXD - main daemon...
Feb 19 22:52:05 hyper lxd[28767]: lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2017-02-19T22:52:05-0600
Feb 19 22:52:05 hyper lxd[28767]: error: UNIQUE constraint failed: storage_pools.name
Feb 19 22:52:05 hyper systemd[1]: lxd.service: Main process exited, code=exited, status=1/FAILURE
Feb 19 23:02:05 hyper lxd[28768]: error: LXD still not running after 600s timeout.
Feb 19 23:02:05 hyper systemd[1]: lxd.service: Control process exited, code=exited status=1
Feb 19 23:02:05 hyper systemd[1]: Failed to start LXD - main daemon.
Feb 19 23:02:05 hyper systemd[1]: lxd.service: Unit entered failed state.
Feb 19 23:02:05 hyper systemd[1]: lxd.service: Failed with result 'exit-code'.
Feb 19 23:02:05 hyper systemd[1]: lxd.service: Service hold-off time over, scheduling restart.
Feb 19 23:02:05 hyper systemd[1]: Stopped LXD - main daemon.
Feb 19 23:02:05 hyper systemd[1]: Starting LXD - main daemon...
Feb 19 23:02:05 hyper lxd[30727]: lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2017-02-19T23:02:05-0600
Feb 19 23:02:06 hyper systemd[1]: Started LXD - main daemon.
Feb 19 23:02:06 hyper systemd[1]: Stopping LXD - main daemon...
Feb 19 23:02:06 hyper systemd[1]: Stopped LXD - main daemon.
Feb 19 23:02:06 hyper systemd[1]: Starting LXD - main daemon...
Feb 19 23:02:06 hyper lxd[30798]: lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2017-02-19T23:02:06-0600
Feb 19 23:02:06 hyper systemd[1]: Started LXD - main daemon.
Feb 19 23:04:20 hyper systemd[1]: Stopping LXD - main daemon...
Feb 19 23:04:20 hyper systemd[1]: Stopped LXD - main daemon.
Feb 19 23:04:25 hyper systemd[1]: Stopped LXD - main daemon.
Feb 19 23:06:05 hyper systemd[1]: Starting LXD - main daemon...
Feb 19 23:06:05 hyper lxd[31617]: lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2017-02-19T23:06:05-0600
Feb 19 23:06:06 hyper systemd[1]: Started LXD - main daemon.
```

```
# lxc info
config:
  storage.zfs_pool_name: tank/lxd
apiextensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
apistatus: stable
apiversion: "1.0"
auth: trusted
public: false
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFSTCCAzGgAwIBAgIQEQN0VPYedVPWE6T6MVILjzANBgkqhkiG9w0BAQsFADAz
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRMwEQYDVQQDDApyb290QGh5
    cGVyMB4XDTE3MDEyOTAyNDAwNVoXDTI3MDEyNzAyNDAwNVowMzEcMBoGA1UEChMT
    bGludXhjb250YWluZXJzLm9yZzETMBEGA1UEAwwKcm9vdEBoeXBlcjCCAiIwDQYJ
    KoZIhvcNAQEBBQADggIPADCCAgoCggIBAOuQwFoYXcahiocVO5YOHvCd8LvJq9bD
    V2UjBr97MQoicpjKrwvlM4CAtFJKquZcDevtXIqDWDBWHkYCynf8qodeUCN+BFs6
    pA8yqBkhbE1nnYB41VNnEaS90+nMRF1iy4Iv3xu2H1tCjBdEsebgDgPI0EvCXhHl
    VwhLWZVLklx0HVfB/AXyQXoT9wWOdBSMozD6cpOLHuNrQ/gkbXwuKtjU+pjf+rp8
    ngdJ1BErN3waVjwCn/+ESaWgz+z/gVnnryLQTgfVRH314AoBqnK2A6j6FrdBwsAt
    /pY32nC3Fw07mNz6s4p3QSGnYrM2+f935+4vPqrV8Pd2775dXUzCcSRA/Vz4z8Nh
    kOR+b9thSvtmc1uNfYpqhq/RWd5JCcAIL76q4g4/JSlY8m0Vg4RZvbex55otduvl
    DZ24eT8IcaDfJTg7Bzb1bUQ75c9YarayQa0yepO4hdO7LZYahwVFYVYgfWDEd6dP
    dOL1epRSGQpLTd51bOlVaygr7SUGA0YKlE17sk+c22C7O0R9iNrd9kiT8mlb49aD
    ypPag+sqCmWdU2xo2SUk3suty7LJOOZ1AnpRJnVIlEMkiD6JQTq+PdVgu6Eg3g5X
    KD4/hgUSM1zrKfpr+76w5B+lylKHte14f/hBgB8wD95/+cwBX9t++236LFA8/nsL
    1lYCseRb5GybAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggr
    BgEFBQcDATAMBgNVHRMBAf8EAjAAMCIGA1UdEQQbMBmCBWh5cGVyhwQKHwEFhwQK
    AAMBhwTAqHoBMA0GCSqGSIb3DQEBCwUAA4ICAQCdpZzPS+G01p2//P/Ha/jrcHoG
    1t8ncbYeBQudqRzXJCGX4/A1xoIpnFxKBSo5S+te1iW2ahYLSObusOXOEsoUAN+3
    wAhVlOjRDG+G8AoXwqkbrr4xMJOTlofFAPDzUJ2y5l08kQgA+5Y69STLkT7FuIJj
    ttiMWuK1yQBSW7f9YyQ2xKm6ALGjxtw2w1HyZdyApSjD7LoyDb12mYTPuakcweLP
    RCngjGQSzS1Tz1VUp9IoWk8KXzVjb9DFWOGkDeV6XbJFjOSziMlK0fVthWNXez5e
    1w/F/xFc1GEFLvn4YXk5LMM8qd1IDZbgkhxSZrEqu4ywzmNSmX3dgDBEuY9wEGoI
    6dgA40J+4NCwmCp6lAf3K9beUq1SquwbO+jxpG8rEwPCzAgVmAubq3xizi/GZHlq
    qLSlRUzi2/MbK3DEzxvN3O4o9GzDsBbIhN7HJw+FuGKjIujwPlPmYBavG3qEWhgO
    1SlUKJKFuJ2XO+jSXGek8lrPsU75zGMV66zebq37AxdZnccgzhH4/bEkFySkbioB
    DMUiFkYzWnC16cOaKV6iyCVLkan+FiMQsj1xMNYxhiKz6mefHGQ96kJ7ArTHoaCb
    I/W/tpLMEIzirmx5McqJ7o1pl5dX6MFdrLDQIedwRMONc+DTS0+4vQ5VWuBOVHB3
    A733RtnwVv2OWHYb2w==
    -----END CERTIFICATE-----
  certificatefingerprint: 502d01293ba62609d8585b9e2e5e372034f497002475f1cce61ab32ef764706c
  driver: lxc
  driverversion: 2.0.7
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-62-generic
  server: lxd
  serverpid: 31617
  serverversion: "2.8"
  storage: zfs
  storageversion: "5"
```

```
# lxc config show
config:
  storage.zfs_pool_name: tank/lxd
```

**Comment by cerealcable** [comment]
Also of interesting note, I was able to stop/start a container that I didn't care too much about, everything worked. Noting the upgrade log where the name "bitnode" is referenced, that is the first container alphabetically so maybe it only got to doing anything with that?

I also made note that I restored the backup database after downgrading if that means much of anything and I would assume zfs wouldn't be changing the data paths?

**Comment by stgraber** [comment]
@cerealcable yeah, if your problem is the same as what I hit on one of my machines and what some other hit, that container failed to get unmounted and crashed the upgrade code. So that container may be at risk if you stop/start it, same goes for the next one alphabetically. The others shouldn't have been touched at all and so should be fine.

Yeah, the DB downgrade could only really work if done after reverting the code, otherwise LXD would have re-upgraded the database during the package downgrade. What's not covered by the DB downgrade is the disk changes that the upgrade would have done. Things like changing the symlinks in /var/lib/lxd/containers, removing the .zfs entries in /var/lib/lxd/containers and /var/lib/lxd/images, creating a whole bunch of stuff under /var/lib/lxd/storage-pools/, ...

**Comment by cerealcable** [comment]
Right so I did replace the database after downgrading so who knows. This is just my home lab at least so this is just something to figure out and get past. Not sure what the next steps are, wouldn't be opposed to hearing any thoughts.

**Comment by stgraber** [comment]
@cerealcable we're working on a LXD 2.9.2 release which will fix all the major issues we're aware of, including being able to recover from a partial upgrade as best we can.

I've helped a few users who ran into the same failure you did recover from it and get a working LXD 2.9.1, but since you downgrade to LXD 2.8 and have things working, I'd recommend staying on LXD 2.8 until we have LXD 2.9.2 out.

**Comment by stgraber** [comment]
We'll also be waiting until we're done dealing with any report of broken upgrades before we push LXD 2.9.x to xenial-backports and yakkety-backports where most of the users for those feature releases are.

That should limit the user base to those who use the LXD snap, Ubuntu development release or LXD PPA. Which is a tiny fraction of our user base and who's typically more tech savvy which helps us with tracking down those issues.

**Comment by cerealcable** [comment]
Not sure if this is going to be important but at one point while messing around with lxd I did delete the default profile because I felt like it, not sure if that's of concern with the upgrade or not.

Should I not use the stable ppa as a stable release channel? I don't really have a reason to not be using a bit more bleeding edge for my home lab but if the ppa stable isn't the right place for more serious usage than my home lab I would like to know and probably would be beneficial for some sort of information somewhere? I know that's not very helpful at all.

**Comment by Rydako** [comment]
Glad to see the problem has already been identified. Updated my custom profile, and we're a go again.

**Comment by nakatadim** [comment]
I got the same after the upgrade to 2.9- i was able to resolve the issue by updating containers_profiles with records for the container's snapshots as well as the snapshot itself. The upgrade had updated just the container's "containers_profiles" aka. echo "insert into containers_profiles(container_id,profile_id,apply_order) values(XX,Y,Z);" | sqlite3 /var/lib/lxd/lxd.db

**Comment by stgraber** [comment]
@cerealcable The LXD feature releases get new releases at least once a month. We do support those releases so it's not like a development build or anything. However for people who need absolute stability and several years of support with nothing being added or change, we have the LTS branch (2.0.x) for that.

So typically developers and home labs will play with the latest features and so the feature releases work fine for them. Production environments do tend to stick to the LTS branch as they don't care so much about new features and just want all the bugfixes, stability and support.

**Comment by stgraber** [comment]
This issue should now have been resolved in git and in LXD 2.9.2, closing.

If anyone who has installed LXD 2.9.2 runs into something like this, please file another issue.

**Comment by ThinGuy** [comment]
Hey Stéphane,
Not sure if you have this all worked out in 2.9.2, but my upgrade from 2.8 failed as well. Two different boxes with one thing in common, they both had non-standard zfs pool names.  While I've re-inited lxd, and can now launch machines I still can't get the zpool name (kept at default) from lxc info/config, which breaks other things I do to ensure the zpool is large enough.  ;),


```
~$ journalctl --unit=lxd
-- Logs begin at Die 2017-02-21 20:15:32 PST, end at Mit 2017-02-22 09:47:10 PST. --
Feb 21 20:15:40 OrangeBox20 systemd[1]: Starting LXD - main daemon...
Feb 21 20:15:40 OrangeBox20 lxd[4103]: lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2017-02-21T20:15:40-0800
Feb 21 20:15:40 OrangeBox20 lxd[4103]: lvl=eror msg="Error checking storage pool \"lxd_zfs\": Unable to import the ZFS pool: cannot import '/var/lib/lxd/disks/lxd_zfs.img
```
```
`~$ lxc info
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 172.27.22.1:8443
  - 172.27.20.1:8443
  - 192.168.100.1:8443
  - 10.99.0.1:8443
  - 10.73.67.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFbjCCA1agAwIBAgIRAPeIVbWredhC2wX8fKqtsyMwDQYJKoZIhvcNAQELBQAw
    OTEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEZMBcGA1UEAwwQcm9vdEBP
    cmFuZ2VCb3gyMDAeFw0xNzAyMjIwNzQyNTBaFw0yNzAyMjAwNzQyNTBaMDkxHDAa
    BgNVBAoTE2xpbnV4Y29udGFpbmVycy5vcmcxGTAXBgNVBAMMEHJvb3RAT3Jhbmdl
    Qm94MjAwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDDgz2XN4j05f2e
    EQVoJDLfGkCeUGoV/DT7fCiM24v4/07EePtTnNkJeuN9sPDwc2jp862ImNRIRoJi
    IPIiyfu/vnIxcb/3Lt7U30wFirz9JOaUYaqhqKGPaJZd5Z375VeLY/GoeWNBxJEv
    z14EtyYwPdgS4Q51ihGhzkRd4kba8cibeCQ3okYqd9y46wa7ldcI2foRtrHpr4qe
    AcP6ZFh5lWeKQzI3KxuAD5HYWHnVHUuwSgsMRZhluXZFgkmQiFn5JO8RfFZKmrZW
    zq5+P5Ly5aV8CNGel/KdPL+3RI5jqqyndfBMCcCubOwnl/54N+QHPrBg2Y8ehrAI
    3sPPsaNPJRE6dR2pLQNPECDmpW+LkD6LFJHaOIQjI4jVnQpNGsxLwqLMk+JjgkKI
    a6irZMaOrpOhcVCEzT0Xc3TW0rh7PYIQaNAuA0ST3zdpbuepx2AwQoxaKAXibOOO
    RTle2/Czmr3blr6rAeNPYwitTKWuhrMeO37Q+SfNC8W/+6EQ2VS8C7RYh07hH0zL
    eOGbvKE10z2ATCxoeJqccuf4GIWijWk77G+zHuLX1G/YPq8MT+Fnm3Fiq/zi09hw
    YdtjFUy26cTiqFXNwbJEd+nz3GaB+e5oPIsj9Qu7+6HM+1jIu1DCWnUzrv0Scc3P
    d/VLxXqqatI9ONoZODA4ZSPe06cqZwIDAQABo3EwbzAOBgNVHQ8BAf8EBAMCBaAw
    EwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADA6BgNVHREEMzAxggtP
    cmFuZ2VCb3gyMIcErBsWAYcErBsUAYcEwKhkAYcECmMAAYcECmMAAYcEClKsATAN
    BgkqhkiG9w0BAQsFAAOCAgEActG1+tf6tbTfWjt+k8K9QK1g4WAmV9BDkaAJSzLD
    SMK2PI70s1iTzbGgU6tv4r9U4WjO95whATKcZRg8eAW5pVDd4zKNp5JcfHNXs+91
    vRR9BmGfGl/R5QjgHkQsVsvQnkD+Jy0LVDmjK4SCAb95LPl/1V+JQxjcxxzfqIoG
    agF3Ya9OrXJZqx8kBLUTO5xFOeAT03U+xajN9nKmIXNCwHkaipmKf9Yt1U8RgKTw
    WLU5FDyDdfsuo6L57Gn5AHFzh7jOarDAlT7OpwwLlvFrahBXiba/itULUDlIPZwK
    /I3Wn4W7dyG4ALaXILmuhuoEmyiVj7JdsX+W+bUVSkgQBplBMlSz4fVhwREejxsE
    AO6R6zZBFdjwdpKCnjBfkQLYTM1jfMmvNGC/1czxNy4iwnhyX7Bn2cEEDX0rqk6D
    YuWHX3SgfQJtfu8uFbggx9FIphh/GN/ovB/B7k2HrxqQzvqvXxGOK2ZRWvKaX72/
    9ZrboUdMYhKj+hDEkonWZ79a8UpmNj67hpvMVCYkF2Fw9PA3hbVRoL82jnH89Ufe
    6NOZuqJLkbJCTGkLXYseKI3+GH9eg7EG7jv47ch78oH6/cKxn9QPqCxv8WkEo5XU
    kZo1fI1Ds/93qySV/zo5vujkCeQRf9xApSl2l+2KZOv+yXZTQZscYKCfrr937UI6
    DUg=
    -----END CERTIFICATE-----
  certificate_fingerprint: f83ae3e1b58b0216c189c2a86921324141b80ed4445a524f009046a23f59c398
  driver: lxc
  driver_version: 2.0.7
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-64-generic
  server: lxd
  server_pid: 30803
  server_version: 2.9.2
  storage: zfs
  storage_version: 0.6.5.6-0ubuntu15
```
```
```
~$ lxc config show
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
```
:~$ sudo zpool status
  pool: default
 state: ONLINE
  scan: none requested
config:

	NAME                              STATE     READ WRITE CKSUM
	default                           ONLINE       0     0     0
	  /var/lib/lxd/disks/default.img  ONLINE       0     0     0

errors: No known data errors
```
```
sudo zpool list
NAME      SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
default  74.5G  10.1G  64.4G 
```

**Comment by stgraber** [comment]
What does "lxc storage list" look like?

**Comment by ThinGuy** [comment]
Ooh.  Cool!
```
~$ lxc storage list
+---------+--------+--------------------------------+---------+
|  NAME   | DRIVER |             SOURCE             | USED BY |
+---------+--------+--------------------------------+---------+
| default | zfs    | /var/lib/lxd/disks/default.img | 58      |
+---------+--------+--------------------------------+---------+
```

**Comment by stgraber** [comment]
Ok, so looks like you got yourself a zpool with a bunch of containers and images on it. Is something actually still broken in your setup?
