### ISSUE TITLE
lxdbr0 improperly created by snap lxd.migrate

### ISSUE THREAD

**Issue by neiloym** [lxc/lxd#4616]
# Required information

 * snap lxd version 3.1
 * lxc info output is item [1] below.

# Issue description

With a xenial machine that already has lxd installed, we are trying to install the snap version of lxd. In installing the snap version of lxd, there is an lxd.migrate script that, when run, produces an unusable lxdbr0. Bring down this network bridge, deleting it, and then creating a new one via lxd init creates a working lxdbr0. 

Prior to running lxd.migrate, we have output [2] below. This is after Step 2 in the reproduction steps.
After running lxd.migrate, we have output [3] below. This is after Step 3 in the reproduction steps.
After recreating the network bridge, we have output [4] below. This is after step 3 in the workaround steps.

# Steps to reproduce

 1. Start with xenial with apt lxd installed.
 2. sudo snap install lxd
 3. sudo lxd.migrate

At this point, the problem is in effect. 

# Steps to workaround

 1. sudo ifconfig lxdbr0 down
 2. sudo brctl delbr lxdbr0
 3. sudo lxd init
Would you like to use LXD clustering? (yes/no) [default=no]:
Do you want to configure a new storage pool? (yes/no) [default=yes]:
Name of the new storage pool [default=default]:
Name of the storage backend to use (btrfs, ceph, dir, lvm, zfs) [default=zfs]:
Create a new ZFS pool? (yes/no) [default=yes]:
Would you like to use an existing block device? (yes/no) [default=no]:
Size in GB of the new loop device (1GB minimum) [default=100GB]:
Would you like to connect to a MAAS server? (yes/no) [default=no]:
Would you like to create a new local network bridge? (yes/no) [default=yes]:
What should the new bridge be called? [default=lxdbr0]:
What IPv4 address should be used? (CIDR subnet notation, “auto” or “none”) [default=auto]: 10.8.8.1/24
Would you like LXD to NAT IPv4 traffic on your bridge? [default=yes]:
What IPv6 address should be used? (CIDR subnet notation, “auto” or “none”) [default=auto]: none
Would you like LXD to be available over the network? (yes/no) [default=no]:
Would you like stale cached images to be updated automatically? (yes/no) [default=yes]
Would you like a YAML "lxd init" preseed to be printed? (yes/no) [default=no]:

At this point, lxdbr0 is reconfigured as needed.

# Additional Information

[1] lxc info
ubuntu@node-amontons:~⟫ lxc info
config:
  core.https_address: '[::]'
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 10.246.114.10:8443
  - 10.8.8.1:8443
  - 10.101.0.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFVTCCAz2gAwIBAgIQUfHN/guto2dIK9dMle5FkzANBgkqhkiG9w0BAQsFADA7
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRswGQYDVQQDDBJyb290QG5v
    ZGUtYW1vbnRvbnMwHhcNMTgwNjAxMTYxNDM1WhcNMjgwNTI5MTYxNDM1WjA7MRww
    GgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRswGQYDVQQDDBJyb290QG5vZGUt
    YW1vbnRvbnMwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCaSytWLv8x
    7seGa1ZQhF8omAzI4dIgMpf9D4yPURj1FevneX3C0K1aDFgLsmX6hzcam7J0wBsr
    CqTAoGP92CoTB3RQE5He3yS6D7a/eEqJ/v5pHIw1kNCMkctnEkX57/jrCgJe9pyJ
    ZFp+w4jmWwJAaA+b0dBcJtjXIzMvhxCfRi6lCkI9fjJC3DWeFiPvXedc9Jcgt2lP
    Snh5A7kM6Hwf6GzwaS8Jfni4TYSNmLR1ETGNFlpthJYkIljc8JqohkBJPrBPYhsF
    bgoRikTmhg03xIyIpe35nXywVqJkECh8LDNIuH+4PbLeNxHZM4qgEMCShbV63mCW
    L6TP5h7h2YRe1lK986LgwXhAmz27hES1qbdvM3RcoTZZApzAU6DbWt/Bv93PdZWU
    wmgC6VNI6s2ORBq8HNHm3R5x6oeSfE1wZn6aJqwFh5kB99YWvKZ6VjNE9He5V3Nr
    m7/JtVeHSjZGahOqrKot4HfPWMEYLzh0gZlBn4YbcTbB/+9asmyrpgeSk8uqy7WH
    GeXkHjjvUbhhCC7wkXT9SSC265rWyMZ4j+yfUKkqedo3VbPN8OS3c+ME7+uG2mwE
    UK+9PJHB+08gfhymsK88bBDIp32BErX6Nj9o8K6Eqm0bHs0LkQXUBFl8vL4gcvX5
    JCpVh9rvC7T1imqxhwgwC1jq3E6cDrgESwIDAQABo1UwUzAOBgNVHQ8BAf8EBAMC
    BaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADAeBgNVHREEFzAV
    gg1ub2RlLWFtb250b25zhwQK9nIKMA0GCSqGSIb3DQEBCwUAA4ICAQCHHeQzLaig
    2jW1Nr0sruYE2jVaQtcYt3XbdVTMiBmcXZrWE7J0oJHj6ZpcvdvbQz4bqCvaC0dv
    ug6Uc9g8sJlN18lF+lYFi2Xj5rGIsDH0u4DR+Izd3i87iU8Z6BXGkj6lG6528WeR
    vUeaVqKDgvmEMWNjpg2jmheQSDoMJDlxh/SEt1CLggD/EBucpp199K6ZTYqsTapy
    QbHbHGFfmgTUyK2VRsP5UA16TmIiVP+VvcZIZu4AjfoPHYkf1lLxuCaXEofscsZG
    H8gr4AYPGidiI1zufGXIqXmDBxWc3Lqegk2ORgohR4556uDUhiOhVZfcl3aJqE2l
    QL+25C1BEgxyFKzxcE4qu5ZmBOrqkDAx7L6940L94j44cAFVKVAlJdXM5dftBHxP
    85ykJqIx2ioZw+Cb1kSH1eeCibiVosCgnzH6+02hdgl2oSrl7Hz/nRUrvM7aEdje
    ft1fM6mzohseuxhpixIaHQoqF5/pUg+u9R+rhnCXKgVantfaYvvrxNzTGEUBRVU9
    t1mafgMod95V7myerX4f9kXLnqb4LwdhF3WilfJpI5objEx8EUiNUqBa9y4K+oKu
    7BnT1HH1sHYwGtXn/QRtTLkfxO4AINXzZ2HRPNnFVJckJ+SF87baJdEX9kcZZrJJ
    vfWJWupWAvlHSCVaKA4QtJ126j3N/rXyyg==
    -----END CERTIFICATE-----
  certificate_fingerprint: 7c749a84d2b5b25f48be8bd743cc6b83b39a4b780953592aa59820ec2f0018a8
  driver: lxc
  driver_version: 3.0.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-127-generic
  server: lxd
  server_pid: 82934
  server_version: "3.1"
  storage: btrfs | zfs
  storage_version: 4.4 | 0.6.5.6-0ubuntu20
  server_clustered: false
  server_name: node-amontons
ubuntu@node-amontons:~⟫ 

```
[2] Pre-lxd.migrate
ubuntu@node-amontons:\~⟫ which lxd
/usr/bin/lxd
ubuntu@node-amontons:\~⟫ lxd --version
2.0.11
ubuntu@node-amontons:\~⟫ brctl show
bridge name     bridge id               STP enabled     interfaces
ubuntu@node-amontons:\~⟫ 
```

```
[3] Post-lxd.migrate
ubuntu@node-amontons:\~⟫ which lxd
/snap/bin/lxd
ubuntu@node-amontons:\~⟫ lxd --version
3.1
ubuntu@node-amontons:\~⟫ brctl show
bridge name     bridge id               STP enabled     interfaces
lxdbr0          8000.000000000000       no
ubuntu@node-amontons:\~⟫ lxc network list
If this is your first time running LXD on this machine, you should also run: lxd init
To start your first container, try: lxc launch ubuntu:16.04

+----------+----------+---------+-------------+---------+
|   NAME   |   TYPE   | MANAGED | DESCRIPTION | USED BY |
+----------+----------+---------+-------------+---------+
| eno1     | physical | NO      |             | 0       |
+----------+----------+---------+-------------+---------+
| eno2     | physical | NO      |             | 0       |
+----------+----------+---------+-------------+---------+
| eno3     | physical | NO      |             | 0       |
+----------+----------+---------+-------------+---------+
| eno4     | physical | NO      |             | 0       |
+----------+----------+---------+-------------+---------+
| enp3s0f0 | physical | NO      |             | 0       |
+----------+----------+---------+-------------+---------+
| enp3s0f1 | physical | NO      |             | 0       |
+----------+----------+---------+-------------+---------+
| lxdbr0   | bridge   | NO      |             | 0       |
+----------+----------+---------+-------------+---------+
ubuntu@node-amontons:\~⟫ lxc network show lxdbr0
config: {}
description: ""
name: lxdbr0
type: bridge
used_by: []
managed: false
status: ""
locations: []
ubuntu@node-amontons:\~⟫ 

ifconfig for lxdbr0
lxdbr0    Link encap:Ethernet  HWaddr 9e:7f:3f:55:3e:91  
          inet6 addr: fe80::9c7f:3fff:fe55:3e91/64 Scope:Link
          inet6 addr: fe80::1/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:470 (470.0 B)
```

```
[4] Post-lxd init
ubuntu@node-amontons:\~⟫ which lxd
/snap/bin/lxd
ubuntu@node-amontons:\~⟫ lxd --version
3.1
ubuntu@node-amontons:\~⟫ brctl show
bridge name     bridge id               STP enabled     interfaces
lxdbr0          8000.000000000000       no
ubuntu@node-amontons:\~⟫ lxc network list
+----------+----------+---------+-------------+---------+
|   NAME   |   TYPE   | MANAGED | DESCRIPTION | USED BY |
+----------+----------+---------+-------------+---------+
| eno1     | physical | NO      |             | 0       |
+----------+----------+---------+-------------+---------+
| eno2     | physical | NO      |             | 0       |
+----------+----------+---------+-------------+---------+
| eno3     | physical | NO      |             | 0       |
+----------+----------+---------+-------------+---------+
| eno4     | physical | NO      |             | 0       |
+----------+----------+---------+-------------+---------+
| enp3s0f0 | physical | NO      |             | 0       |
+----------+----------+---------+-------------+---------+
| enp3s0f1 | physical | NO      |             | 0       |
+----------+----------+---------+-------------+---------+
| lxdbr0   | bridge   | YES     |             | 0       |
+----------+----------+---------+-------------+---------+
ubuntu@node-amontons:~⟫ lxc network show lxdbr0
config:
  ipv4.address: 10.8.8.1/24
  ipv4.nat: "true"
  ipv6.address: none
description: ""
name: lxdbr0
type: bridge
used_by: []
managed: true
status: Created
locations:
- none
ubuntu@node-amontons:~⟫ 

ifconfig for lxdbr0:
lxdbr0    Link encap:Ethernet  HWaddr fe:63:4e:3f:33:3d  
          inet addr:10.8.8.1  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::fc63:4eff:fe3f:333d/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:648 (648.0 B)
```

**Comment by stgraber** [comment]
Ok, so I think what happened here is:
1) System had LXD 2.0 pre-installed but never started or configured
2) lxd.migrate caused LXD 2.0 to start, starting up the link-local-only lxdbr0 with it
3) lxd.migrate properly identified this has being an unmodified config so didn't migrate lxdbr0
4) when LXD 2.0 was brought down, lxdbr0 didn't get deleted as lxd-bridge got stopped

Should be pretty trivial to reproduce and sort out in lxd.migrate, we effectively need to make sure that the lxd-bridge unit is also brought down before package removal so that this bridge goes away.

**Comment by ryan-beisner** [comment]
For context, this is a paper cut in the conjure-up flow.  Thanks for having a look.

**Comment by stgraber** [comment]
Fix pushed to the snap packaging branch should be on the stable update of Monday.

**Comment by neiloym** [comment]
Thank you, Stephane. Which version is this going into? I can go ahead and confirm from our end.

**Comment by stgraber** [comment]
@neiloym got released to the stable channel just now. So make sure your snap is up to date before running `lxd.migrate`, `snap refresh lxd` should do that.

**Comment by neiloym** [comment]
@stgraber Stephane, trying to update the snap yields the following output: 
ubuntu@node-sarabhai:~$ sudo snap refresh lxd
snap "lxd" has no updates available
ubuntu@node-sarabhai:~$ 



but it looks as though lxdbr0 still isn't being configured as expected, per the below:
ubuntu@node-sarabhai:~$ sudo lxd.migrate 
=> Connecting to source server
=> Connecting to destination server
=> Running sanity checks
The source server is empty, no migration needed.

The migration is now complete and your containers should be back online.
Do you want to uninstall the old LXD (yes/no) [default=no]? yes

All done. You may need to close your current shell and open a new one to have the "lxc" command work.
To migrate your existing client configuration, move ~/.config/lxc to ~/snap/lxd/current/.config/lxc
ubuntu@node-sarabhai:~$ 
ubuntu@node-sarabhai:~$ 
ubuntu@node-sarabhai:~$ 
ubuntu@node-sarabhai:~$ which lxd
/snap/bin/lxd
ubuntu@node-sarabhai:~$ lxd --version
3.1
ubuntu@node-sarabhai:~$ brctl show
bridge name	bridge id		STP enabled	interfaces
lxdbr0		8000.000000000000	no		
ubuntu@node-sarabhai:~$ lxc network list
If this is your first time running LXD on this machine, you should also run: lxd init
To start your first container, try: lxc launch ubuntu:16.04

+----------+----------+---------+-------------+---------+
|   NAME   |   TYPE   | MANAGED | DESCRIPTION | USED BY |
+----------+----------+---------+-------------+---------+
| eno1     | physical | NO      |             | 0       |
+----------+----------+---------+-------------+---------+
| eno2     | physical | NO      |             | 0       |
+----------+----------+---------+-------------+---------+
| eno3     | physical | NO      |             | 0       |
+----------+----------+---------+-------------+---------+
| eno4     | physical | NO      |             | 0       |
+----------+----------+---------+-------------+---------+
| enp3s0f0 | physical | NO      |             | 0       |
+----------+----------+---------+-------------+---------+
| enp3s0f1 | physical | NO      |             | 0       |
+----------+----------+---------+-------------+---------+
| lxdbr0   | bridge   | NO      |             | 0       |
+----------+----------+---------+-------------+---------+
ubuntu@node-sarabhai:~$ lxc network show lxdbr0
config: {}
description: ""
name: lxdbr0
type: bridge
used_by: []
managed: false
status: ""
locations: []
ubuntu@node-sarabhai:~$ 



Am I missing something in grabbing the most recent stable update?

**Comment by stgraber** [comment]
@neiloym is that on Ubuntu 16.04?

**Comment by neiloym** [comment]
@stgraber Yes, 16.04.

ubuntu@node-sarabhai:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
ubuntu@node-sarabhai:~$

**Comment by neiloym** [comment]
Can confirm now that using the stable update appropriate removes the lxdbr0, leaving a clean slate with which to work. In the context of conjure-up, running the lxd init allows the creation of lxdbr0 as expected without needing to bring down and delete the existing one.
