### ISSUE TITLE
`lxc list` shows containers from former cluster, `lxc cluster list` says the node is not in a cluster

### ISSUE THREAD

**Issue by ChrisLundquist** [lxc/lxd#4705]
# Required information
Ubuntu 18.04
```
config:
  core.https_address: 192.168.4.198:8443
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 192.168.4.198:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFQDCCAyigAwIBAgIQN1mUsxztsDIOXb/HYRkEWDANBgkqhkiG9w0BAQsFADAy
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRIwEAYDVQQDDAlyb290QG51
    YzIwHhcNMTgwNjI1MjA0NjUxWhcNMjgwNjIyMjA0NjUxWjAyMRwwGgYDVQQKExNs
    aW51eGNvbnRhaW5lcnMub3JnMRIwEAYDVQQDDAlyb290QG51YzIwggIiMA0GCSqG
    SIb3DQEBAQUAA4ICDwAwggIKAoICAQC6Hx+jUqJQMuPX5xJjMGLphFm7+LCbBXTR
    M/WWxvJCJt4IG6Eo2Bl6FF1ChntshnroggmhyNNiBKq2WyVcnaYSUplPYNlYukj8
    Pq2aw7hHeX8Jt/QV3maKad2oG9Z2rwaU+E2C380lAJwYrldwx9LErY0A8lKq2/Tg
    MemzgreC7d0I6tqLCOxPfeTrytyWw3J6CXKuwLALA6wp6SoAThsQkCUuFKrKCDxr
    ZkPqBz22OKfqZKzr1mV58o5gPMQo/BP4xQbuQotT+KyNH5IbvU96LvnPLHGXN2Ne
    OtrbxwthLm4jJQsaDSgSSgFH3sT0foMQoOW2McTnZ4bTPlR4bRLg3+Sqf43SInmq
    qBQ+M86k9osb/6gRo1GGRIqAJ54fWD7Tq04O8uV24gd5OvjtlPjs7Yc19vVnYf1C
    o812W+ybh6Z7Ze0/RA9r04HJ0ybxdCyADLHB0GQXIIlKTybOFptZ1WWmHxY/47ee
    fumBunC/L6YPlikSzJWzTD+t6GAnVCDMndOmwvH2aFk/s94zXQ7BWPJDD5idr+zE
    nn67H8quAk12Z7RCSJF9ScUyGTxzP8TmZprxGq/1BxBXbq82AlJwbu9GIDAj9STD
    lmNRNjuVKHdjKAxRhn1J9WsSLt62Di2H+x2922o+ie46iAXnRR4rpE2lH2X5qlQE
    KcSMrTjZRQIDAQABo1IwUDAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYB
    BQUHAwEwDAYDVR0TAQH/BAIwADAbBgNVHREEFDASggRudWMyhwTAqASXhwTAqATD
    MA0GCSqGSIb3DQEBCwUAA4ICAQBhS/v8VUGO6bjVVEDaPVQFAVWFUohCs6MFM/QM
    u0OcdVkOW+OpMbjmYAZIhjwF04uJuZVIrTYW9rht0f2534yJB09LzI1OoUFZn1wU
    hrL/Onygean6eATrT87EJu198BhZ7ikkTu7ZnpNFf0FBsXwnbkjwN93tD6BS34Pb
    uS+3j3ltVVIOHD7GrfBt6JJ6He7KKzewJlyOki5SZvxA/ziNPVuNQSZ4ppmB9xLd
    GRQjkdZ61KqPu74IzbaR/g1VqO8xrnYTKYlHUilJvYspGJ/BBx4uDsSS1SyRbUOP
    QRlYIsPTr+J6dBbdUMVyT9r7r/4yZwYrtZc9DKZ6gb0jJHxzx78w6rJL5qFq2UDW
    dOuIoLmJH+SReE2pWXEmE+BRgWtueFkB1NgtdXTk/qFh6OrC0OZlE1we8KFInRjY
    SiGnR6g5dfT8i5Pu1znTssmb+RS9G38ReyPJgSVB9IjbMucPHw4zCz7BLc2mq9fU
    STEuCbw9isldyW6D5/61hJxIeMFxUYH9l5uoNE/E2C3K8HPbOcFv5XRwRCiHkJsZ
    qFiGjQGCcQ7pjeBG9yMEhWmI3yyoI2iI31BAANP3BNb0lYQa8GEBacj1DU3NJGoQ
    k8m4e4MAVyOcIC4rvdgW1dDYEfaSkKAjOunNM7eh4oTDHJufdGTC1iKReSAAAzfZ
    ADqcSw==
    -----END CERTIFICATE-----
  certificate_fingerprint: c30eba58dad7a18cb4458efa04a5e3bba8e04b308d4046e680f0f16ec5707f60
  driver: lxc
  driver_version: 3.0.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-23-generic
  server: lxd
  server_pid: 13578
  server_version: 3.0.1
  storage: btrfs
  storage_version: 4.15.1
  server_clustered: true
  server_name: ""
```
# Issue description

A node which was previously a cluster member, shows a container running on the former cluster, even when it is not in the cluster any more.
```
clundquist@NUCALASCAGE:~$ lxc list
+-----------+---------+----------------------+------+------------+-----------+----------+
|   NAME    |  STATE  |         IPV4         | IPV6 |    TYPE    | SNAPSHOTS | LOCATION |
+-----------+---------+----------------------+------+------------+-----------+----------+
| pi-hole-1 | RUNNING | 192.168.4.124 (eth0) |      | PERSISTENT | 0         | nuc2     |
|           |         | 192.168.4.123 (eth0) |      |            |           |          |
+-----------+---------+----------------------+------+------------+-----------+----------+
clundquist@NUCALASCAGE:~$ lxc cluster list
Error: LXD server isn't part of a cluster
```

Note, location is `nuc2` which is another distinct member from `nucalascage`

# Steps to reproduce

I'm unsure. 

I built a cluster to test it out. (lxd was running on 16.04 upgraded the nodes and lxd to 18.04)
```
clundquist@nuc2:~$ lxc cluster list
+-------------+----------------------------+----------+--------+-------------------+
|    NAME     |            URL             | DATABASE | STATE  |      MESSAGE      |
+-------------+----------------------------+----------+--------+-------------------+
| NUCALASCAGE | https://192.168.4.198:8443 | YES      | ONLINE | fully operational |
+-------------+----------------------------+----------+--------+-------------------+
| deon        | https://192.168.4.152:8443 | NO       | ONLINE | fully operational |
+-------------+----------------------------+----------+--------+-------------------+
| nuc2        | https://192.168.4.151:8443 | YES      | ONLINE | fully operational |
+-------------+----------------------------+----------+--------+-------------------+
| nuc3        | https://192.168.4.137:8443 | YES      | ONLINE | fully operational |
+-------------+----------------------------+----------+--------+-------------------+
```

Hit a million issues with launching containers 
```
clundquist@nuc3:~$ lxc copy pi-hole-1 pi-hole-2
Error: Failed container creation: UNIQUE constraint failed: storage_volumes.storage_pool_id, storage_volumes.node_id, storage_volumes.name, storage_volumes.type
clundquist@nuc3:~$ lxc copy pi-hole-1 local:pi-hole-2
Error: Failed container creation: no "source" property found for the storage pool
clundquist@nuc3:~$ lxc copy pi-hole-1 local:pi-hole-2
Error: Failed container creation: UNIQUE constraint failed: storage_volumes.storage_pool_id, storage_volumes.node_id, storage_volumes.name, storage_volumes.type
```
  
Tore down the cluster:
```
$ lxc cluster remove deon
Member deon removed
clundquist@nuc2:~$ lxc cluster remove nuc2
Error: node still has the following containers: pi-hole-1
clundquist@nuc2:~$ lxc cluster remove nuc3
Error: node still has the following images: b190d5ec0c537468465e7bd122fe127d9f3509e3a09fb699ac33b0c5d4fe050f
clundquist@nuc2:~$ lxc cluster remove nuc3 --force
Member nuc3 removed
clundquist@nuc2:~$ lxc cluster remove NUCALASCAGE
Error: no "source" property found for the storage pool
clundquist@nuc2:~$ lxc cluster list
+-------------+----------------------------+----------+--------+-------------------+
|    NAME     |            URL             | DATABASE | STATE  |      MESSAGE      |
+-------------+----------------------------+----------+--------+-------------------+
| NUCALASCAGE | https://192.168.4.198:8443 | NO       | ONLINE | fully operational |
+-------------+----------------------------+----------+--------+-------------------+
| nuc2        | https://192.168.4.151:8443 | YES      | ONLINE | fully operational |
+-------------+----------------------------+----------+--------+-------------------+
clundquist@nuc2:~$ lxc cluster remove NUCALASCAGE --force
Member NUCALASCAGE removed
clundquist@nuc2:~$ lxc cluster remove nuc2
Error: node still has the following containers: pi-hole-1
clundquist@nuc2:~$ lxc cluster remove nuc2 --force
Error: server leave failed: http code 403 'failed to leave server 1: Need at least one voter in configuration: {[]}'
```

Now a node which (has left)/(was kicked from) the cluster still has the old state.
```
clundquist@NUCALASCAGE:~$ lxc list
+-----------+---------+----------------------+------+------------+-----------+----------+
|   NAME    |  STATE  |         IPV4         | IPV6 |    TYPE    | SNAPSHOTS | LOCATION |
+-----------+---------+----------------------+------+------------+-----------+----------+
| pi-hole-1 | RUNNING | 192.168.4.124 (eth0) |      | PERSISTENT | 0         | nuc2     |
|           |         | 192.168.4.123 (eth0) |      |            |           |          |
+-----------+---------+----------------------+------+------------+-----------+----------+
```

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by ChrisLundquist** [comment]
It is also worth noting that the kicked member can still `lxc exec` into the container running on a different node.
```
clundquist@NUCALASCAGE:~$ lxc list
+-----------+---------+----------------------+------+------------+-----------+----------+
|   NAME    |  STATE  |         IPV4         | IPV6 |    TYPE    | SNAPSHOTS | LOCATION |
+-----------+---------+----------------------+------+------------+-----------+----------+
| pi-hole-1 | RUNNING | 192.168.4.124 (eth0) |      | PERSISTENT | 0         | nuc2     |
|           |         | 192.168.4.123 (eth0) |      |            |           |          |
+-----------+---------+----------------------+------+------------+-----------+----------+
clundquist@NUCALASCAGE:~$ lxc exec pi-hole-1 bash
root@pi-hole-1:~# exit
```

**Comment by stgraber** [comment]
Yes, that's actually normal. When you use --force, the node is removed from the cluster without knowing that it was removed. So if it was a database node as is the case here, it will still think it's part of a cluster and have an older copy of the database.

When using --force against a node that's still online, you'll need to manually go remove lxd on it to reset it.

**Comment by stgraber** [comment]
Only saw your second comment now, that disconnected node still has a valid copy of the cluster certificate and so can access the API of other compute nodes, which explains why that `lxc exec` worked.

That part isn't really ideal and I'd feel better if a node which was dropped from the cluster wouldn't be allowed to make queries to the cluster, @freeekanayaka is that something you can think about?

Closing the issue as the force removal behavior shown here is consistent. The storage failures shown earlier should have been fixed in LXD 3.0.1/3.2 but likely hit here before the upgrade to 3.0.1 occured.

**Comment by freeekanayaka** [comment]
@stgraber it depends what's the concern: if it's security, the only solution that comes to my mind is to have per-node certificates, and delete a node's certificate when you use --force. If the concern is something else we might do something cheaper.

Regarding the UNIQUE constraint failure and the 'no "source" property found for the storage pool' one, those should be a dupe of #4629, fixed in 3.2.

**Comment by stgraber** [comment]
@freeekanayaka well, it's mostly about not having things be super confusing after a node was forcefully removed. Per-node certs would certainly be neat and let us do that through them, though I wouldn't necessarily count that as added security since all nodes still have the cluster certificate and so while it wouldn't be able to talk to the cluster, it'd still be able to impersonate it (and there's really not much we can do about that, if a node is compromised you must re-generate the cluster cert).
