### ISSUE TITLE
storage volume copy error

### ISSUE THREAD

**Issue by kim0** [lxc/lxd#5348]
Filing this per the discussion in https://github.com/lxc/lxd/issues/5339
Symptom: zfs data volume failing to copy

**Comment by kim0** [comment]
@stgraber .. If you think fixing this would take some time (not a few days) .. any advice on how can I not trigger this error ? Thanks

**Comment by stgraber** [comment]
I'll need to find a way to reproduce it. If it's what I think, I should have a way to do that.
Anyway, I'm busy preparing for LXD 3.8 right now, so it may be a couple of days.

Until I have a reproducer, I can't really provide any workarounds...

Assuming that it is a mount namespace issue, a reboot should fix it.
You may also have some luck by grepping for the volume's name in `/proc/*/mountinfo` to identify what process has it mounted (other than your container), then can try to use `nsenter -t PID -m` and go unmount it in there, see if that helps somehow.

**Comment by kim0** [comment]
@stgraber .. mm I rebooted the box, and copying that volume is still failing! Can you give me the equivalent zfs commands that a volume copy does .. to try doing that by hand, which I'm hoping might return a (better?) error message

**Comment by stgraber** [comment]
Can you show `lxc storage show s`?

**Comment by kim0** [comment]
HYG
```
$ lxc storage show s
config:
  source: zdocker/lxd
  volatile.initial_source: zdocker/lxd
  zfs.pool_name: zdocker/lxd
description: ""
name: s
driver: zfs
used_by:
- /1.0/containers/container-6d8a1e8771ad200e1d616b238125830db412fc86
- /1.0/containers/container-ea258f44566afa4feb9480843af24075b9662d9a
- /1.0/images/84a71299044bc3c3563396bef153c0da83d494f6bf3d38fecc55d776b1e19bf9
- /1.0/profiles/default
- /1.0/storage-pools/s/volumes/custom/blah
- /1.0/storage-pools/s/volumes/custom/blah1
- /1.0/storage-pools/s/volumes/custom/blah2
- /1.0/storage-pools/s/volumes/custom/blah2wsnapshot
- /1.0/storage-pools/s/volumes/custom/blah2wsnapshot1
- /1.0/storage-pools/s/volumes/custom/data-6d8a1e8771ad200e1d616b238125830db412fc86
- /1.0/storage-pools/s/volumes/custom/data-ea258f44566afa4feb9480843af24075b9662d9a
status: Created
locations:
- none
```

**Comment by kim0** [comment]
The debug log file is https://transfer.sh/15v5nb/lxd.log

**Comment by stgraber** [comment]
What do you get if you run:

```
zfs list -t snapshot -o name -H -d 1 -s creation -r zdocker/lxd/custom/data-6d8a1e8771ad200e1d616b238125830db412fc86
zfs snapshot -r zdocker/lxd/custom/data-6d8a1e8771ad200e1d616b238125830db412fc86@copy-send-62682825-20c2-4c41-9c39-f10e9de3bbcf
zfs destroy -r zdocker/lxd/custom/data-6d8a1e8771ad200e1d616b238125830db412fc86@copy-send-62682825-20c2-4c41-9c39-f10e9de3bbcf
```

**Comment by stgraber** [comment]
You need to run those as root

**Comment by stgraber** [comment]
LXD itself always runs as root, regardless of what user the client tool is running as, the client (lxc) just talks to the daemon (lxd) over a unix socket, the daemon then acts as root.

**Comment by kim0** [comment]
Thanks .. Ok I just tried the commands as root, and they all seem to succeed. HYG https://transfer.sh/P75Eu/zfs.log

**Comment by kim0** [comment]
I was trying some lxc commands now, and the lxc socket wasn't responding .. I checked snap and it said it was auto-refreshing for the past 6 hours. Obviously something was wrong! I tried removing lxd and reinstalling, got the below showmount error. I rebooted the box, removed lxd, and reinstalled from --edge .. It's finally back to normal. I then created the container and data volume and I was able to copy it successfully!

```
# snap remove lxd
error: cannot perform the following tasks:
- Stop snap "lxd" services ([--root / is-enabled snap.lxd.activate.service] failed with exit status 1: Failed to get unit file state for snap.lxd.activate.service: No such file or directory
)
- Remove security profile for snap "lxd" (9756) (cannot find installed snap "lxd" at revision 9756: missing file /snap/lxd/9756/meta/snap.yaml)
- Remove data for snap "lxd" (9664) (remove /var/snap/lxd/common/ns/shmounts: device or resource busy)
- Disconnect lxd:network from core:network (snap "lxd" has no "network" plug)
- Disconnect lxd:lxd-support from core:lxd-support (snap "lxd" has no "lxd-support" plug)
- Disconnect lxd:system-observe from core:system-observe (snap "lxd" has no "system-observe" plug)
- Disconnect lxd:network-bind from core:network-bind (snap "lxd" has no "network-bind" plug)
```

**Comment by kim0** [comment]
Let me explain what I'm trying to do. I would like to run a series of shell commands, inside a container + data volume. The goal, is to snapshot both the container + data, after every shell command is executed so I have an audit trail along the way.

To do that, I wrote a small python script, that shells out and runs various lxc commands. When I copied the container, I found it still mounts the old data volume with it. So I detach that, and instead attach the new one. I'm not sure if the commands I'm trying to do are correct, and I'm hitting an error .. not sure if it's a wrong command (likely!) or some weird bug

@stgraber  I'd be very thankful if you could take a look on https://paste.ubuntu.com/p/hdBQDZcWVZ/ and let me know
* Whether those commands are correct for what I want to achieve
* If there's a less set of lxc commands that can achieve the same, please let me know!
* Please confirm if lxc waits until the operation it was invoked to do, is completed before exiting (or not!)

Thanks a lot

**Comment by stgraber** [comment]
Reproduce the issue from your paste, looking into it now.
