### ISSUE TITLE
lxc copy --refresh also copies running state and so starts container on backup server

### ISSUE THREAD

**Issue by idef1x** [lxc/lxd#5759]
Don't know how to reopen a previous issue, but this one might be important
See https://github.com/lxc/lxd/issues/5708 for details.

Since snap 3.13 is out with a fix for the above I spotted a side effect:

refreshing a container backup now also copies the running state. So when I refresh a running container (lxc copy --refresh) it will start it on the backup server, which is not really wanted. In my case the networks are bridged on the backup server with the operational LXD host, so ip conflicts occur (and duplicate macs)

Running on Ubuntu 18.10 with snap 3.13 10756

**Comment by stgraber** [comment]
Fixed already :)

**Comment by idef1x** [comment]
@stgraber Hmm not completely fixed in 3.14 I am afraid...It goes wrong when using projects.
If I do a "lxc copy remote:runningcontainer local: --project test --refresh"
It copies the container and in STOPPED state. So far so good, but when you do a "lxc config show local:runningcontainer --project test" it shows:

volatile.last_state.power: RUNNING

which results in a running container locally when:
- the local host reboots (not tested, but assumed for now)
- the local host goes into suspend mode (systemctl suspend) and then gets resumed. Tested since my backup LXD host goes to sleep at night and at resume the containers were running.

**Comment by stgraber** [comment]
Right, guess we'll need to special case that one key then.

**Comment by idef1x** [comment]
The problem still exists in 3.16. Copying/refreshing goes fine and the container is in stopped state on the backup server, but the power state (volatile.last_state.power: RUNNING) is still running.
There also seems to be a running LXD process that checks regurly for stopped containers and starts it when the volatile.last_state.power: RUNNING is set in the config. 
So after the backup (copy/refresh) I still have to stop the containers.

**Comment by stgraber** [comment]
@idef1x 
https://github.com/lxc/lxd/pull/6093

**Comment by idef1x** [comment]
Really thanks again :)

**Comment by idef1x** [comment]
hmmm looks to be working fine for the last power state settings, but apparently I also have a few containers with boot.autostart set to true. So will always be started when LXD (re)starts. Not sure if that should be an issue, since I specifically had set it. If you think that those values could be stripped as well, then I'll leave my backup script as is, otherwise I'll have to adapt it myself afterwards.

**Comment by stgraber** [comment]
I don't think we'd want to strip that one as that may cause some surprises.

In your case it may be best to not set that property on your containers directly but instead rely on a profile to set it, you can then have that profile set it to true on your main host and false on your fallback host.

**Comment by idef1x** [comment]
That's actually a good idea! I'll do that..Thanks
