### ISSUE TITLE
Verbose option does not output anything

### ISSUE THREAD

**Issue by keestux** [lxc/lxd#8005]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The summary output of "lxc info":
```
  driver: lxc
  driver_version: 4.0.4
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 5.4.0-29-generic
  os_name: Ubuntu
  os_version: "20.04"
  project: default
  server: lxd
  server_clustered: true
  server_name: ijssel
  server_pid: 968857
  server_version: "4.6"
  storage: lvm
  storage_version: 2.02.176(2) (2017-11-03) / 1.02.145 (2017-11-03) / 4.41.0
```

# Issue description

Using `--verbose` with `lxc move` or `lxc copy` does not give progress information as it used to.

# Steps to reproduce

Just create a new container and copy or move it to a different node on the cluster (or any other remote)
```
lxc init ubuntu:18.04 c1
lxc copy --verbose c1 c2 --target luts
```

**Comment by stgraber** [comment]
Are you sure you were getting progress information when copying within a cluster instead of between remotes?

**Comment by stgraber** [comment]
In any case, it's something that we should report progress for, I'm just trying to figure out if it's an actual regression rather than just a case where progress details were not added.

**Comment by keestux** [comment]
I don't know about within a cluster. We started using the cluster just recently.
So, you're saying with remotes you get verbose, but not within a cluster. If that is so, then it is not intuitive.

**Comment by stgraber** [comment]
Yeah, in some cases we should be able to provide the progress data here.

`lxc copy a b --target blah` in a cluster is using the same code path as a local `lxc copy a b` which also does not provide you with progress details.

**Comment by stgraber** [comment]
Whereas a `lxc copy remote1:a remote2:b` uses a different API (migration) with the client talking to both servers and getting progress data from both sides. (In the other cases, the client only talks to a single server)

**Comment by gzhang1218** [comment]
Hi, I'm a student at UT Austin working with some other students looking for issues to contribute to. If possible, could my group claim this issue to work on for our virtualization class? Thanks!

**Comment by stgraber** [comment]
Done, assigned it to you!

**Comment by gzhang1218** [comment]
Hey @stgraber, I'm having a little trouble getting started on this issue, if you have some time, some guidance would be greatly appreciated. Thanks!

**Comment by stgraber** [comment]
An in-cluster copy is initiated through `POST /1.0/instances/NAME` which hits `instance_post.go`.
You then hit the `targetNode != ""` of `containerPost` which eventually gets you onto the migration logic with two possible outcomes:
 - containerPostClusteringMigrateWithCeph
 - containerPostClusteringMigrate

Looking at that latter, it sets up a function called `run` which performs an API move (copy+delete).
It has access to the operation (`op` variable) but never updates its metadata so the client never gets any progress during such an operation.

To do this, you'd want that run() function to use `dest.GetEvents()` to get access to the event stream, filter those events to only get those you care about for the `dest.CopyInstance` call (similar to what we do in lxc/copy.go) but instead of printing those events to the user on the command line, you'll instead put them into `op` using `op.UpdateMetadata`, effectively relaying them to the user.

The `containerPostClusteringMigrateWithCeph` case is trivially solved with this tiny patch:
```
diff --git a/lxd/instance_post.go b/lxd/instance_post.go
index 218602a6b..3b2a05035 100644
--- a/lxd/instance_post.go
+++ b/lxd/instance_post.go
@@ -430,7 +430,7 @@ func containerPostClusteringMigrate(d *Daemon, c instance.Instance, oldName, new
 
 // Special case migrating a container backed by ceph across two cluster nodes.
 func containerPostClusteringMigrateWithCeph(d *Daemon, c instance.Instance, projectName, oldName, newName, newNode string, instanceType instancetype.Type) response.Response {
-       run := func(*operations.Operation) error {
+       run := func(op *operations.Operation) error {
                // If source node is online (i.e. we're serving the request on
                // it, and c != nil), let's unmap the RBD volume locally
                logger.Debugf(`Renaming RBD storage volume for source container "%s" from "%s" to "%s"`, c.Name(), c.Name(), newName)
@@ -453,7 +453,7 @@ func containerPostClusteringMigrateWithCeph(d *Daemon, c instance.Instance, proj
                }
 
                // Trigger a rename in the Ceph driver.
-               err = pool.MigrateInstance(c, nil, &args, nil)
+               err = pool.MigrateInstance(c, nil, &args, op)
                if err != nil {
                        return errors.Wrap(err, "Failed to rename ceph RBD volume")
                }
```

**Comment by gzhang1218** [comment]
Thanks so much for the help @stgraber! I've been trying to figure out how to filter the events for the `CopyInstance` call by looking at lxc/copy.go and other files which use `dest.getEvents()` but I'm still not really sure how I would go about filtering the events from a listener object returned by `dest.getEvents()`. I see some code regarding a ProgressRenderer but I'm not entirely sure how to use this.

Also, when would the metadata of `op` need to be updated in run(), after everything (including copying, deleting, and renaming, and restoring the original value of volatile.apply_template), or just after `CopyInstance()` (since we're filtering for events only concerning `CopyInstance`)?

**Comment by stgraber** [comment]
GetEvents() gets you an EventListener, you call AddHandler on that to record a handler for the type you care about (in this case `operation`).

You then have the function you passed to that handler get called every time an operation is updated, you then need to match that with the operation id you got from the CopyInstance call, if they match, you then get the Metadata of that operation and use it to update your own operation with op.UpdateMetadata, effectively forwarding the Metadata change.

**Comment by stgraber** [comment]
@gzhang1218 Do you still intend to work on this or should we un-assign so someone else can have a go at it?

**Comment by presztak** [comment]
@stgraber Can this one be my next task?
